using Microsoft.CodeAnalysis;

namespace Server.Core.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class MinimalApiRequestDelegateSourceGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        static string indent(int depth = 1) => new(' ', 4 * depth);

        context.AddSource($"Generated.MinimalApiRequestDelegates.g.cs",
        $$"""
        // <auto-generated/>
        using Microsoft.AspNetCore.Http;
        using Microsoft.AspNetCore.Mvc;

        namespace {{context.Compilation.AssemblyName}};

        public static partial class Generated
        {
            public static (string Route, Delegate Delegate)[] MinimalApiRequestDelegates { get; } =
            [
                {{string.Join("\n" + indent(2), Shared.Constants.Endpoints.Select(e =>
                    $"(\"{e.Route}\", ([FromQuery] {e.Type} q, HttpResponse r) => r.WriteAsJsonAsync(q)),"))}}
            ];
        }
        """);
    }
}
